eureka:
    instance:
      hostname: localhost
    client:
      register-with-eureka: false
      fetch-registry: false

spring:
  main:
    banner-mode: false

logging:
  level:
    root: warn

server:
  port: 8761